[package]
name = "route_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
lightning-invoice = "0.33"
bitcoin = "0.30"
bech32 = "0.9"
hex = "0.4"